backend/apis/urls.py
from django.urls import path, include
from apis.views import StudentRegisterView, UserLoginAPIView, AlumniLoginView, StudentRegistrationAPIView, \
    AlumniRegistrationAPIView, StudentLoginView, StudentViewSet, AlumniViewSet, VerifyEmailView, AlumniDetailViewSet, StudentDetailViewSet, \
    home, EditAlumniViewSet,EditStudentViewSet, AlumniLogoutView, filter_students, get_branches_dropdown, get_current_sem_dropdown,\
    upload_resume, check_resume, resume_view
    
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import obtain_auth_token
from django.conf import settings
from django.conf.urls.static import static


router = DefaultRouter()
router.register('alumni', AlumniViewSet, basename='alumni')
router.register('students', StudentViewSet, basename='student')
router.register('alumnidetails', AlumniDetailViewSet, basename='alumnidetails') 
router.register('studentsdetails', StudentDetailViewSet, basename='studentdetails')

# new

#router.register('editalumnidetails', EditAlumniViewSet, basename='editalumnidetails') 
'''
router.register('alumni', AlumniViewSet, basename='alumni')

router.register('students', StudentViewSet, basename='student')

router.register('studentregister/', StudentRegistrationAPIView, basename='studentregister')
router.register('studentsregister', StudentRegisterView, basename='studentsregister')'''
#router.register('users', UserViewSet)
urlpatterns = [
    path('api/', include(router.urls)),
    path('', home, name='frontpage' ),
    path('alumnilogin/', AlumniLoginView.as_view(), name='alumnilogin'),
    path('logout/', AlumniLogoutView.as_view(), name='alumni_logout'),
    path('studentlogin/', StudentLoginView.as_view(), name='studentlogin'),
    path('studentregister/', StudentRegistrationAPIView.as_view(), name='studentregister'), # actual
    path('alumniregister/', AlumniRegistrationAPIView.as_view(), name='alumniregister'), # actual
    #path('login/', UserLoginAPIView.as_view(),name='login'), #actual login
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    path('verify-email/', VerifyEmailView.as_view(), name='verify_email'),
    path('get_branches_dropdown/', get_branches_dropdown, name='get_branches_dropdown' ),
    path('get_current_sem_dropdown/', get_current_sem_dropdown, name='get_current_sem_dropdown' ),
    path('filter_students/', filter_students, name='filter_students' ),


   path('api/editalumnidetails/<int:user_id>/', EditAlumniViewSet.as_view(),name='edit_alumni'),
   path('api/editstudentdetails/<int:user_id>/', EditStudentViewSet.as_view(),name='edit_student'),

   path('upload_resume/<int:user_id>/', upload_resume, name='upload_resume'),
   path('resume_view/<int:user_id>/', resume_view),
   #check_resume
   path('check_resume/<int:user_id>/', check_resume),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework.authtoken.views import obtain_auth_token


admin.site.site_header='Alumni Student job portal Admin'
admin.site.site_title='Alumni Student job portal Admin panel'
admin.site.index_title='Portal Administration'
urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^',include('apis.urls')),
    re_path(r'^',include('jobs.urls')),
    path('auth/', obtain_auth_token)
]

backend/jobs/urls.py
from django.urls import path, include

from .views import add_job, frontpage, CountsView, get_job_counts, get_jobs_by_user, JobViewSet, CreateJobView, TotalCountsView, \
 location_list, company_list, filter_jobs, get_job_details, get_recommendations, apply_job, get_applied_counts, linkedin_jobs, \
 get_location_suggestions, naukri_jobs, naukri_recommended_jobs, get_naukri_recommendations, nlocation_list, ncompany_list, \
 nsalary_list, nexperience_needed_list, get_collaborative_recommendations, click_job, get_ncollaborative_recommendations

urlpatterns = [
    path('add/', add_job, name='add_job'),
    path('viewjobs', frontpage , name='viewJobs'),
    path('count/', CountsView.as_view(), name='count'),
    path('totalcount/', TotalCountsView.as_view(), name='totalcount'),
    path('userjobcount/<int:user_id>', get_job_counts, name='userjobcount'),
    path('jobappliedcounts/<int:user_id>', get_applied_counts, name='get_applied_counts'),
    path('userpostedjobs/<int:user_id>', get_jobs_by_user, name='userjob'),
    path('jobs/<int:pk>', JobViewSet.as_view(), name='jobs'),
    path('createjobs/', CreateJobView.as_view(), name='createjobs'),
    path('jobs/', filter_jobs, name='job_list'),
    path('jobs/locations/', location_list, name='job_location_list'),
    path('jobs/companies/', company_list, name='job_company_list'),
    path('jobs/nlocations/', nlocation_list, name='njob_location_list'),
    path('jobs/ncompanies/', ncompany_list, name='njob_company_list'),
    path('jobs/nsalary/', nsalary_list, name='nsalary_list'),
    path('jobs/nexperience/', nexperience_needed_list, name='nexperience_needed_list'),
    path('jobdetails/<int:job_id>/', get_job_details, name='job-detail'),
    path('jobrecommendations/', get_recommendations, name='job-recommendations'),

    path('naukrijobrecommendations/', get_naukri_recommendations, name='get_naukri_recommendations'),

    path('applyJob/', apply_job, name='apply_job'),

    path('clickjob/', click_job, name='click_job'),

    path('linkedinjobs/', linkedin_jobs, name='linkedin_jobs'),
    path('api/locations', get_location_suggestions, name='get_location_suggestions'),
    path('naukrijobs/', naukri_jobs, name='naukri_jobs'),
    path('naukrirecommendedjobs/<str:title>/<str:location>/', naukri_recommended_jobs, name='naukri_recommended_jobs'),

    path('collaborativejobrecommendations/', get_collaborative_recommendations, name='get_collaborative_recommendations'),
    path('ncollaborativejobrecommendations/', get_ncollaborative_recommendations, name='get_collaborative_recommendations'),
]

backend/jobs/models.py
# Create your models here.
from django.db import models
from apis.models import PortalUser
from django.contrib.postgres.fields import ArrayField

class Job(models.Model):
    title = models.CharField(max_length=255)
    short_description = models.TextField()
    long_description = models.TextField()
    location = models.CharField(max_length=255)
    company_name = models.CharField(max_length=455)
    posted_by = models.ForeignKey(PortalUser, on_delete=models.CASCADE)
    pay_offered = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=10, choices=(("active", "Active"), ("hidden", "Hidden"),("hired","Hired")))
    skills_required = ArrayField(models.CharField(max_length=60), blank=True)
    job_offer_type = models.CharField(max_length=10, choices=(("intern", "Intern"), ("fulltime", "Full-Time")))
    posted_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'jobs'

    def __str__(self):
        return self.title
    
    

class Application(models.Model):
    job = models.ForeignKey('Job', on_delete=models.CASCADE)
    content = models.TextField()
    experience = models.TextField()
    created_by = models.ForeignKey(PortalUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=(("active", "Active"), ("closed", "Closed")), default="active")

    class Meta:
        db_table = 'applications'

class Clicked(models.Model):
    other_job = models.ForeignKey('OtherJobs', on_delete=models.CASCADE)
    created_by = models.ForeignKey(PortalUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'other_jobs_clicked'

class OtherPortals(models.Model):
    portal_name = models.CharField(max_length=255)

    class Meta:
        db_table = 'other_portals'

    def __str__(self):
        return self.portal_name

class OtherJobs(models.Model):
    title = models.CharField(max_length=355)
    company_name = models.CharField(max_length=455)
    location = models.CharField(max_length=255)
    description = models.TextField()
    link = models.TextField()
    experience_needed = models.CharField(max_length=100)
    salary = models.CharField(max_length=100)
    skills_required = ArrayField(models.CharField(max_length=355), blank=True)
    other_portal = models.ForeignKey('OtherPortals', on_delete=models.CASCADE)
    status = models.CharField(
        max_length=10,
        choices=[('active', 'Active'), ('closed', 'Closed')],
        default='active'
    )

    class Meta:
        db_table = 'other_jobs'

    def __str__(self):
        return self.title

backend/jobs/forms.py
from django import forms

from .models import Job

class AddJobForm(forms.ModelForm):
    
    class Meta:
        model = Job
        fields = ['title', 'short_description', 'long_description', 'location', 'company_name', 'pay_offered', 'skills_required', 'job_offer_type']

backend/jobs/templates/add_job.html
{% extends 'alumnibase.html' %}

{% block content %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
    <div id="add-job-app">
        <h1 style="color: rgb(16, 55, 90); margin-left: 230px;">Add job</h1>

        <form v-on:submit="validateForm" method="post" action=".">
            {% csrf_token %}

            {% if form.errors %}
            <label> You forgot to add</label>
                {% for error in form.errors %}
                    <div >
                       <label> {{ error }}</label> 
                    </div>
                {% endfor %}
            {% endif %}

            <div class="field">
                <label>Title</label>

                <div class="control">
                    <input class="input" type="text" name="title" id="id_title" v-model="title" placeholder="Job Title">
                </div>
            </div>

            <div class="field">
                <label>Short description</label>

                <div class="control">
                    <textarea class="textarea" name="short_description" id="id_short_description" v-model="short_description" placeholder="desc"></textarea>
                </div>
            </div>

            <div class="field">
                <label>Long description</label>

                <div class="control">
                    <textarea class="textarea" name="long_description" id="id_long_description" placeholder="Description"></textarea>
                </div>
            </div>

            <div class="field">
                <label>Company name</label>

                <div class="control">
                    <input class="input" type="text" name="company_name" id="id_company_name" v-model="company_name" placeholder="Company name">
                </div>
            </div>

            <div class="field">
                <label>location</label>

                <div class="control">
                    <input class="input" type="text" name="location" id="id_location" placeholder="city">
                </div>
            </div>

            <div class="field">
                <label>Pay offered</label>

                <div class="control">
                    <input class="input" type="text" name="pay_offered" id="id_pay_offered" placeholder="ex: 2000000">
                </div>
            </div>

            <div class="field">
                <label>Skills required</label>
                <div class="control">
                    <input type="text" name="new_skill"  id="new_skills" >
                    <input type="button" value="Add Skills" onclick="addSkill()" id="add-skills-button">
                </div>
                <ul id="skills_list"></ul>
            </div>
            


            <div class="field">
                <label>Job offer type</label>

                <div class="control">
                    <div class="select">
                        <select name="job_offer_type" v-model="job_offer_type">
                            <option value="">Choose offer type</option>
                            <option value="intern">Intern</option>
                            <option value="fulltime">Full-Time</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <button  type="submit">Add</button>
                </div>
            </div>
        </form>
    </div>

    <style>
        #add-job-app {
  max-width: 600px;
  margin: 0 auto;
}

.button {
  background-color: #1b5188e9;
  border-color: #1b5188e9;
  color: #fff;
  font-weight: bold;
  padding: 0.5rem 0.75rem;
}

.button:hover,
.button:focus {
  background-color: #24709f;
  border-color: #1e4e97;
}
form {
            max-width: 500px;
            margin: auto;
            padding: 20px;
            border: 1px solid #1b5188e9;
            border-radius: 5px;
            color: #060633;
            background-color: #1b5188e9;;
        }
        ul{
            background-color:  aliceblue;
            color:  #1b5188e9;
            border: none;
            border-color: black;
            margin-top: 10px;
            border-radius: 5px;
            cursor: pointer;
            font-family: Arial, Helvetica, sans-serif;
            width: 80px;

        }
        h1{
            color: #060633;
        }
        h3{
            color: red;
        }
        label {
            display: block;
            margin-bottom: 5px;
            font-weight: bold;
            color: #060633;
        } 
        input[type="text"] {
            width: 100%;
            padding: 5px;
            align-content: center;
            box-sizing: border-box;
        }
        input[type="button"] {
            background-color:#060633;
            color:  #ccc;
            border: none;
            padding: 10px;
            margin-top: 10px;
            border-radius: 5px;
            cursor: pointer;
            font-family: Arial, Helvetica, sans-serif;
        }
        input[type="button"]:hover {
            background-color:#4396e9e9;
            color: #ccc;
        }
        button{
            background-color:#060633;;
            color:  #ccc;
            border: none;
            padding: 10px;
            margin-top: 10px;
            border-radius: 5px;
            cursor: pointer;
            font-family: Arial, Helvetica, sans-serif;
            width: 80px;
        }
        button:hover {
            background-color:#4396e9e9;
            color: #ccc;
        }
    </style>
    <script>
        function addSkill() {
        const skillInput = document.getElementById("new_skills");
        const skill = skillInput.value.trim();

        if (skill) {
            const skillsList = document.getElementById("skills_list");
            const newSkill = document.createElement("li");
            newSkill.innerHTML = skill;
            skillsList.appendChild(newSkill);
            skillInput.value = "";
            skills_required = skillsList;
        }
    }
    </script>
{% endblock %}

{% block scripts %}
<script>
    

    const AddJobApp = {
        data() {
            return {
                title: '',
                company_name: '',
                short_description: '',
                job_offer_type: '',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                this.errors = []

                if (this.title === '') {
                    this.errors.push('The title field is missing!')
                }

                if (this.short_description === '') {
                    this.errors.push('The short description field is missing!')
                }

                if (this.company_name === '') {
                    this.errors.push('The company name field is missing!')
                }

                if (this.job_offer_type === '') {
                    this.errors.push('The job_offer_type is missing!')
                }

                if (this.errors.length) {
                    e.preventDefault()

                    return false
                } else {
                    return true
                }
            }
        }
    }

    Vue.createApp(AddJobApp).mount('#add-job-app');
</script>
{% endblock %}

backend/jobs/templates/viewjobs.html
{% extends "studentbase.html" %}

{% block content %}
<style>
    .job-card {
  border: 1px solid #ccc;
  border-radius: 4px;
  padding: 10px;
  margin-bottom: 20px;
  transition: box-shadow 0.3s ease;
  box-shadow: 0px 0px 5px #ccc;
  background-color: aliceblue;
  width: 60%;
}

.job-card:hover {
  box-shadow: 5px  5px 5px #9b2b2b;
  cursor: pointer;
  animation: bounce_613 0.4s linear;
}

.job-card h5 {
  margin-bottom: 10px;
}

.job-card p {
  margin-bottom: 5px;
}

.job-card .details {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

</style>
  <h2>Active Job Listings</h2>
  {% if jobs %}
    <div class="job-list">
      {% for job in jobs %}
        <div class="job-card">
          <h1>{{ job.title }}</h1>
          <p>{{ job.short_description }}</p>
          <p><strong>Location:</strong> {{ job.location }}</p>
          <p><strong>Company:</strong> {{ job.company_name }}</p>
          <p><strong>Pay Offered:</strong> Rs:{{ job.pay_offered }}</p>
          <p><strong>Skills Required:</strong> {{ job.skills_required }}</p>
          <p><strong>Skills Required:</strong> {% for jobs in job.skills_required %}</p>
          <li> {{jobs}}</li>
          {% endfor %}
          <div class="details">
            <a href="#" class="btn">View</a>
            <small>{{ job.posted_on|date:"F j, Y" }}</small>
          </div>
        </div>
      {% endfor %}
    </div>
  {% else %}
    <p>No active jobs available.</p>
  {% endif %}
{% endblock %}